FROM python:3.7-slim

RUN apt-get update \
   && apt-get install -y git gnupg2 software-properties-common curl \
   && apt-key adv --keyserver keyserver.ubuntu.com --recv-keys CE7709D068DB5E88 \
   && add-apt-repository 'deb https://repo.sovrin.org/sdk/deb bionic stable' \
   && apt-get update \
   && apt-get install -y libindy libnullpay

RUN mkdir -p /aries-backchannels
WORKDIR /aries-backchannels

ADD https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 ./jq
RUN chmod +x ./jq

COPY python/requirements.txt python/
COPY mock/requirements-latest.txt mock/
COPY mock/mock-agent mock-agent
RUN pip install -r mock/requirements-latest.txt && pip install -r python/requirements.txt

# Copy the necessary files from the AATH Backchannel sub-folders
COPY python python
COPY mock mock
COPY data ./

# mock is in /usr/local/bin. The Backchannel is looking for it in ./bin, create a link to it in ./bin
RUN mkdir -p bin
RUN ln -fs ./mock-agent/version.py bin/mock
RUN ls -alh mock
RUN find "$PWD" -name mock
RUN ls -alh bin
RUN find "$PWD" -name bin

ENV PYTHONPATH=/aries-backchannels
ENV RUNMODE=docker

#RUN ls -alh /usr/local/bin
RUN ls -alh bin
#RUN ls -alh /aries-backchannels/mock*
#RUN ./bin/mock --version > ./mock-version.txt

RUN python bin/mock
RUN python bin/mock > ./mock-version.txt
RUN cat ./mock-version.txt

ENTRYPOINT ["bash", "mock/ngrok-wait.sh"]
